name: 'Getting WARP+ Traffic'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '5 0 * * *'

jobs:
  auto_getting_traffic:
    runs-on: ubuntu-latest
    timeout-minutes: 1500
    steps:
      - name: 'Checking'
        uses: actions/checkout@v2

      - name: 'Setting Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Getting WARP+ Traffic'
        timeout-minutes: 1440
        env:
          DEVICEID: ${{ secrets.DEVICEID }}
          TERM: xterm
        run: python warp.py
